// This houses the whole game data
const game = {
  level: [
    {
      name: "CyberPunk City",
      image: "",
      mode: [
        {
          difficulty: "easy",
          characters: [
            {
              name: "",
              title: "",
              image: "",
              xCoord: "",
              yCoord: "",
              isFound: false,
            },
            {
              name: "",
              title: "",
              image: "",
              xCoord: "",
              yCoord: "",
              isFound: false,
            },
            {
              name: "",
              title: "",
              image: "",
              xCoord: "",
              yCoord: "",
              isFound: false,
            },
            {
              name: "",
              title: "",
              image: "",
              xCoord: "",
              yCoord: "",
              isFound: false,
            },
            {
              name: "",
              title: "",
              image: "",
              xCoord: "",
              yCoord: "",
              isFound: false,
            },
          ],
        },
        {
          difficulty: "hard",
          characters: [
            {
              name: "",
              title: "",
              image: "",
              xCoord: "",
              yCoord: "",
              isFound: false,
            },
            {
              name: "",
              title: "",
              image: "",
              xCoord: "",
              yCoord: "",
              isFound: false,
            },
            {
              name: "",
              title: "",
              image: "",
              xCoord: "",
              yCoord: "",
              isFound: false,
            },
            {
              name: "",
              title: "",
              image: "",
              xCoord: "",
              yCoord: "",
              isFound: false,
            },
            {
              name: "",
              title: "",
              image: "",
              xCoord: "",
              yCoord: "",
              isFound: false,
            },
          ],
        },
      ],
    },
    {
      name: "Universe 113",
      image: "",
      mode: [
        {
          difficulty: "easy",
          characters: [
            {
              name: "",
              title: "",
              image: "",
              xCoord: "",
              yCoord: "",
              isFound: false,
            },
            {
              name: "",
              title: "",
              image: "",
              xCoord: "",
              yCoord: "",
              isFound: false,
            },
            {
              name: "",
              title: "",
              image: "",
              xCoord: "",
              yCoord: "",
              isFound: false,
            },
            {
              name: "",
              title: "",
              image: "",
              xCoord: "",
              yCoord: "",
              isFound: false,
            },
            {
              name: "",
              title: "",
              image: "",
              xCoord: "",
              yCoord: "",
              isFound: false,
            },
          ],
        },
        {
          difficulty: "hard",
          characters: [
            {
              name: "",
              title: "",
              image: "",
              xCoord: "",
              yCoord: "",
              isFound: false,
            },
            {
              name: "",
              title: "",
              image: "",
              xCoord: "",
              yCoord: "",
              isFound: false,
            },
            {
              name: "",
              title: "",
              image: "",
              xCoord: "",
              yCoord: "",
              isFound: false,
            },
            {
              name: "",
              title: "",
              image: "",
              xCoord: "",
              yCoord: "",
              isFound: false,
            },
            {
              name: "",
              title: "",
              image: "",
              xCoord: "",
              yCoord: "",
              isFound: false,
            },
          ],
        },
      ],
    },
    {
      name: "Ultimate Space Battle",
      image: "",
      mode: [
        {
          difficulty: "easy",
          characters: [
            {
              name: "",
              title: "",
              image: "",
              xCoord: "",
              yCoord: "",
              isFound: false,
            },
            {
              name: "",
              title: "",
              image: "",
              xCoord: "",
              yCoord: "",
              isFound: false,
            },
            {
              name: "",
              title: "",
              image: "",
              xCoord: "",
              yCoord: "",
              isFound: false,
            },
            {
              name: "",
              title: "",
              image: "",
              xCoord: "",
              yCoord: "",
              isFound: false,
            },
            {
              name: "",
              title: "",
              image: "",
              xCoord: "",
              yCoord: "",
              isFound: false,
            },
          ],
        },
        {
          difficulty: "hard",
          characters: [
            {
              name: "",
              title: "",
              image: "",
              xCoord: "",
              yCoord: "",
              isFound: false,
            },
            {
              name: "",
              title: "",
              image: "",
              xCoord: "",
              yCoord: "",
              isFound: false,
            },
            {
              name: "",
              title: "",
              image: "",
              xCoord: "",
              yCoord: "",
              isFound: false,
            },
            {
              name: "",
              title: "",
              image: "",
              xCoord: "",
              yCoord: "",
              isFound: false,
            },
            {
              name: "",
              title: "",
              image: "",
              xCoord: "",
              yCoord: "",
              isFound: false,
            },
          ],
        },
      ],
    },
  ],
};
export default game;
